SCHEMA_METADATA_INDEX = "business_schema_metadata"

SCHEMA_METADATA = [
    {
        "table": "purchase_orders",
        "column": "po_number",
        "business_name": "Purchase Order Number",
        "description": "Unique purchase order identifier such as PO1001.",
        "data_type": "string",
        "examples": ["PO1001", "PO2500"],
    },
    {
        "table": "purchase_orders",
        "column": "supplier_id",
        "business_name": "Supplier",
        "description": "Supplier associated with the purchase order.",
        "data_type": "foreign_key",
        "examples": ["supplier of PO1001", "orders by supplier"],
    },
    {
        "table": "purchase_orders",
        "column": "order_date",
        "business_name": "Purchase Order Date",
        "description": "Date when the purchase order was created.",
        "data_type": "date",
        "examples": ["orders created today", "orders this month"],
    },
    {
        "table": "purchase_order_items",
        "column": "commit_qty",
        "business_name": "Committed Quantity",
        "description": "Quantity committed by supplier for a purchase order line.",
        "data_type": "decimal",
        "examples": ["committed quantity of PO1001", "average committed quantity"],
    },
    {
        "table": "purchase_order_items",
        "column": "order_qty",
        "business_name": "Purchase Order Quantity",
        "description": "Ordered quantity for a purchase order line.",
        "data_type": "decimal",
        "examples": ["purchase order quantity", "ordered quantity by material"],
    },
    {
        "table": "suppliers",
        "column": "code",
        "business_name": "Supplier Code",
        "description": "Unique supplier code used in procurement reporting.",
        "data_type": "string",
        "examples": ["supplier ABC", "supplier SUP0001"],
    },
    {
        "table": "suppliers",
        "column": "name",
        "business_name": "Supplier Name",
        "description": "Human-readable supplier name.",
        "data_type": "string",
        "examples": ["who is supplier of PO1001"],
    },
    {
        "table": "materials",
        "column": "material_code",
        "business_name": "Material Code",
        "description": "Unique material identifier such as MAT100 or MAT0100.",
        "data_type": "string",
        "examples": ["material MAT100", "stock for MAT0100"],
    },
    {
        "table": "inventory",
        "column": "stock_qty",
        "business_name": "Available Stock",
        "description": "Current stock quantity available for a material.",
        "data_type": "decimal",
        "examples": ["stock available for material MAT100"],
    },
    {
        "table": "inventory",
        "column": "reserved_qty",
        "business_name": "Reserved Stock",
        "description": "Quantity reserved and not freely available for new demand.",
        "data_type": "decimal",
        "examples": ["reserved quantity", "available minus reserved"],
    },
    {
        "table": "sales_orders",
        "column": "so_number",
        "business_name": "Sales Order Number",
        "description": "Unique sales order identifier.",
        "data_type": "string",
        "examples": ["sales order SO1001"],
    },
    {
        "table": "sales_orders",
        "column": "customer_id",
        "business_name": "Customer",
        "description": "Customer associated with the sales order.",
        "data_type": "foreign_key",
        "examples": ["top customers by order quantity"],
    },
    {
        "table": "sales_orders",
        "column": "order_date",
        "business_name": "Sales Order Date",
        "description": "Date when the sales order was created.",
        "data_type": "date",
        "examples": ["orders created today", "orders this month"],
    },
    {
        "table": "sales_order_items",
        "column": "order_qty",
        "business_name": "Sales Order Quantity",
        "description": "Quantity ordered by a customer for a sales order line.",
        "data_type": "decimal",
        "examples": ["top 5 customers by order quantity"],
    },
    {
        "table": "customers",
        "column": "code",
        "business_name": "Customer Code",
        "description": "Unique customer code used in sales reporting.",
        "data_type": "string",
        "examples": ["customer CUST00001"],
    },
    {
        "table": "customers",
        "column": "name",
        "business_name": "Customer Name",
        "description": "Human-readable customer name.",
        "data_type": "string",
        "examples": ["top customers"],
    },
    {
        "table": "order_schedule",
        "column": "scheduled_date",
        "business_name": "Scheduled Date",
        "description": "Planned delivery or fulfillment date for an order line.",
        "data_type": "date",
        "examples": ["scheduled this week", "upcoming schedules"],
    },
    {
        "table": "shipment",
        "column": "shipped_qty",
        "business_name": "Shipped Quantity",
        "description": "Quantity shipped against a sales order.",
        "data_type": "decimal",
        "examples": ["shipped quantity", "shipments this month"],
    },
    {
        "table": "invoice",
        "column": "total_amount",
        "business_name": "Invoice Amount",
        "description": "Total invoice value for a sales order.",
        "data_type": "decimal",
        "examples": ["invoice amount", "revenue this month"],
    },
]
